# Nome da Action  
name: Snake Game

# Controlador do tempo que será feito a atualização dos arquivos
on:
  schedule:
    # Será atualizado a cada 5 horas
    - cron: "0 */5 * * *"

  # Permite executar manualmente
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão necessária para push no repositório

    steps:
      # Faz checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Gera a animação Snake (apenas SVG)
      - name: Gerar a animação Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: vpsilvaa  # Substitua pelo seu nome de usuário
          outputs: dist/github-contribution-grid-snake.svg

      # Verifica status do repositório
      - run: git status

      # Push das alterações para a branch de saída
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # Certifique-se de que essa branch existe
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
